### ISSUE TITLE
compile  v7.4.0 seems to be failed

### ISSUE THREAD

**Issue by HoneyLuka** [iorate/ublacklist#204]
I can't determine why it failed, it was fine until this version.
Is it related to my Node version?

When I run ```yarn```
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @docsearch/react@npm:3.0.0-alpha.42 [0fc9e] doesn't provide @algolia/client-search (pc747e), requested by @algolia/autocomplete-preset-algolia
➤ YN0002: │ @docusaurus/plugin-debug@npm:2.0.0-beta.14 [f11c8] doesn't provide webpack (p590e4), requested by @docusaurus/utils
➤ YN0002: │ @docusaurus/plugin-sitemap@npm:2.0.0-beta.14 [f11c8] doesn't provide webpack (pf1f72), requested by @docusaurus/utils
➤ YN0002: │ @docusaurus/theme-classic@npm:2.0.0-beta.14 [f11c8] doesn't provide webpack (pc0079), requested by @docusaurus/utils
➤ YN0002: │ @docusaurus/theme-search-algolia@npm:2.0.0-beta.14 [f11c8] doesn't provide prism-react-renderer (p2b3f7), requested by @docusaurus/theme-common
➤ YN0002: │ @docusaurus/theme-search-algolia@npm:2.0.0-beta.14 [f11c8] doesn't provide webpack (p8f347), requested by @docusaurus/utils
➤ YN0002: │ @docusaurus/utils-validation@npm:2.0.0-beta.14 [387a6] doesn't provide webpack (p79c09), requested by @docusaurus/utils
➤ YN0002: │ addons-linter@npm:2.13.1 doesn't provide @types/download (pdc215), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:2.13.1 doesn't provide body-parser (p99bff), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:2.13.1 doesn't provide download (pe5d6a), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:2.13.1 doesn't provide express (p5a480), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:2.13.1 doesn't provide safe-compare (p08478), requested by addons-scanner-utils
➤ YN0002: │ react-dev-utils@npm:12.0.0-next.47 doesn't provide typescript (pb3be1), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:12.0.0-next.47 doesn't provide webpack (pc383a), requested by fork-ts-checker-webpack-plugin
➤ YN0060: │ ublacklist-website@workspace:website provides react (p3fdc4) with version 17.0.2, which doesn't satisfy what @docusaurus/core and some of its descendants request
➤ YN0002: │ ublacklist@workspace:. doesn't provide react (p5f082), requested by react-colorful
➤ YN0002: │ ublacklist@workspace:. doesn't provide react-dom (p132cd), requested by react-colorful
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 337ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 472ms
➤ YN0000: ┌ Link step
➤ YN0076: │ esbuild-android-arm64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-darwin-arm64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-freebsd-64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-freebsd-arm64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-32@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-mips64le@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-ppc64le@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-s390x@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-netbsd-64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-openbsd-64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-sunos-64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-32@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-arm64@npm:0.14.9 The darwin-x64 architecture is incompatible with this module, link skipped.
➤ YN0007: │ esbuild@npm:0.14.9 must be built because it never has been before or the last one failed
➤ YN0007: │ simple-git-hooks@npm:2.7.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.20.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.6.5 must be built because it never has been before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.20.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ dtrace-provider@npm:0.8.8 must be built because it never has been before or the last one failed
➤ YN0007: │ spawn-sync@npm:1.0.15 must be built because it never has been before or the last one failed
➤ YN0007: │ ublacklist@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 19s 485ms
➤ YN0000: Done with warnings in 20s 547ms
```

When I run ```yarn build safari production```
```
[webpack-cli] Failed to load '/Users/selina/Documents/project/uBlacklist/webpack.config.ts' config
[webpack-cli] Error: Cannot find module 'node:fs'
Require stack:
- /Users/selina/Documents/project/uBlacklist/node_modules/globby/index.js
- /Users/selina/Documents/project/uBlacklist/webpack.config.ts
- /Users/selina/Documents/project/uBlacklist/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/selina/Documents/project/uBlacklist/node_modules/webpack-cli/lib/bootstrap.js
- /Users/selina/Documents/project/uBlacklist/node_modules/webpack-cli/bin/cli.js
- /Users/selina/Documents/project/uBlacklist/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/selina/Documents/project/uBlacklist/node_modules/globby/index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.extensions..js (/Users/selina/Documents/project/uBlacklist/node_modules/esbuild-register/dist/node.js:4803:15)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/selina/Documents/project/uBlacklist/node_modules/globby/index.js',
    '/Users/selina/Documents/project/uBlacklist/webpack.config.ts',
    '/Users/selina/Documents/project/uBlacklist/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/selina/Documents/project/uBlacklist/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/selina/Documents/project/uBlacklist/node_modules/webpack-cli/bin/cli.js',
    '/Users/selina/Documents/project/uBlacklist/node_modules/webpack/bin/webpack.js'
  ]
}
ERROR: "webpack --env browser=safari --env mode=production --env typecheck=notypecheck" exited with 2.
```

## Specifications

- OS: macOS 12.2 with M1 chip
- Node: /usr/local/bin/node v15.5.1
- NPM: /usr/local/bin/npm v7.3.0
- Yarn: /usr/local/bin/yarn v3.1.1

**Comment by iorate** [comment]
@HoneyLuka 
Please use Node >= 16.
I introduced globby instead of glob in this commit https://github.com/iorate/ublacklist/commit/66402c11a8954796bb33274a94335b9cdb202b9d , and globby internally uses [node: imports](https://nodejs.org/dist/latest-v17.x/docs/api/esm.html#node-imports) ([ref](https://github.com/sindresorhus/globby/issues/184)), which is supported only in Node >=14.13.1 or >=16.0.0.

**Comment by HoneyLuka** [comment]
@iorate Yes, it indeed a node version issue, finally I use nvm to install v16 node, instead of the system node. Thank you!
